#!/usr/bin/env bash
# Install Nginx on  web-01 server

apt-get -y update
apt-get -y install nginx
mkdir --parents /var/www/html
echo 'Holberton School' > /var/www/html/index.html
service nginx restart
