#!/usr/bin/env bash
# Bash script with the minimum number of commands to automate Nginx fix
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
