#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes
#display hours from 0 to 12
#display minutes from 1 to 59


hour=0
minute=60
while [ $hour -le 13 ]; do
if [ $minute -eq 60 ]; 
then
if [ $hour -le 12 ];
then
    echo "Hour: $hour";
fi;
    hour=$(( hour + 1 ));
    minute=1
else
    echo "$minute";
    minute=$(( minute + 1));
fi;
done
